name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install -f

      # Set environment variables using GitHub Secrets
      - name: Set up environment variables
        run: |
          echo "REACT_APP_API_KEY_GITHUB=${{ secrets.REACT_APP_API_KEY_GITHUB }}" >> .env
          echo "REACT_APP_GITHUB_USER=${{ secrets.REACT_APP_GITHUB_USER }}" >> .env
          echo "REACT_APP_API_KEY_NASA=${{ secrets.REACT_APP_API_KEY_NASA }}" >> .env
          
          

      # Build the app
      - name: Build the app
        run: npm run build
        env:
          CI: false

      - name: Configure Git for deployment
        run: |
          git config --global user.email "a0989718985@gmail.com"
          git config --global user.name "jerry19980310"
          git remote get-url origin || git remote add origin https://github.com/jerry19980310/MyPortfolio.git
          git remote set-url origin https://x-access-token:${{ secrets.REACT_APP_API_KEY_GITHUB }}@github.com/jerry19980310/MyPortfolio.git

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: 
          npm run deploy
